//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MidiSeqMS.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MidiSeqMSTYPE               130
#define ID_WINDOW_MANAGER               131
#define IDB_BITMAP_QUARTERREST          132
#define IDB_SIXTEENTHREST               133
#define IDB_EIGHTHREST                  134
#define IDB_FLAT                        136
#define IDB_SHARP                       137
#define IDB_QUARTERREST_INVERT          138
#define IDB_INVEIGTH                    139
#define IDB_INVSIXTEENTH                140
#define IDB_INVTHIRTY                   141
#define IDB_NOTE_WHOLE                  142
#define IDB_NOTE_HALF                   143
#define IDB_NOTE_QUARTER                144
#define IDB_NOTE_EIGTH                  145
#define IDB_NOTE_SIXTEENTH              146
#define IDB_NOTE_THIRTYSECOND           147
#define IDB_HALFREST                    148
#define IDB_WHOLEREST                   149
#define IDB_MEASUREBAR                  150
#define IDB_NOTETIE                     151
#define IDB_ACCENT                      152
#define IDB_DOT                         153
#define IDB_TRIPLET                     154
#define IDB_BLOCK_MOVE                  155
#define IDB_BLOCK_COPY                  156
#define IDB_BLOCK_INCREASE              157
#define IDB_BLOCK_DECREASE              158
#define IDB_BLOCK_CHANGEINSTRUMENT      159
#define IDB_BLOCK_CHANGEDUR             160
#define IDB_BLOCKUP                     161
#define IDB_BLOCKDOWN                   162
#define IDB_BLOCK_REPEAT                163
#define IDB_INKEY                       164
#define IDD_DIALOG_SELECTMIDI           165
#define IDB_NATURAL                     165
#define IDB_TIMESIG_2_2                 181
#define IDB_TIMESIG_3_2                 182
#define IDB_TIMESIG_2_4                 183
#define IDB_TIMESIG_3_4                 184
#define IDB_TIMESIG_4_4                 185
#define IDB_TIMESIG_5_4                 186
#define IDB_TIMESIG_6_8                 187
#define IDD_DIALOG_PARAMETER            188
#define IDB_TEMPO                       189
#define IDB_LOUDNESS                    190
#define IDB_INST_CHANGE                 191
#define IDB_QUARTERNOTE_EQ              192
#define IDD_DIALOG_SELECT_DURATION      193
#define IDB_BLOCK_INSERT                195
#define IDB_BLOCK_MIDIINPUT             196
#define IDB_DECOR_NONE                  199
#define IDD_DIALOG_NOTEPROPERTIES       200
#define IDD_DIALOG_SELECTOR             202
#define IDD_DIALOG_STRINGSELECTOR       204
#define IDD_DIALOG_ENTERSTRING          311
#define IDB_CB_REST_WHOLE               319
#define IDB_CB_REST_HALF                320
#define IDB_CB_REST_QUARTER             321
#define IDB_CB_REST_SIXTEENTH           322
#define IDB_CB_EIGTH                    323
#define IDB_BITMAP1                     324
#define IDB_CB_REST_THIRTYSECOND        324
#define IDB_CB_TIMESIG_2_4              327
#define IDB_CB_TIMESIG_2_2              328
#define IDB_CB_TIMESIG_3_2              329
#define IDB_CB_TIMESIG_4_4              330
#define IDB_CB_TIMESIG_5_4              331
#define IDB_CB_TIMESIG_6_8              332
#define IDB_CB_TIMESIG_3_4              333
#define IDB_THIRTYSEC_REST              335
#define IDB_CB_REST_EIGTH               336
#define IDB_BITMAP3                     338
#define IDB_CB_MISC_ENDBAR              338
#define IDB_BITMAP4                     349
#define IDB_BUTTON_PLAY_UP              350
#define IDB_BUTTON_PLAY_DOWN            351
#define IDB_BUTTON_STOP_DOWN            355
#define IDB_BUTTON_STOP_UP              356
#define IDB_CB_DECORATIONS_ACCENT_NOTSEL 357
#define IDB_CB_DECORATIONS_ACCENT_SEL   358
#define IDB_CB_DECORATIONS_DOTTED_NOTSEL 359
#define IDB_CB_DECORATIONS_DOTTED_SEL   360
#define IDB_CB_DECORATIONS_NONE         361
#define IDB_CB_DECORATIONS_TRIPLET_NOTSEL 362
#define IDB_CB_DECORATIONS_TRIPLET_SEL  363
#define IDB_CB_ACCIDENTAL_FLAT          364
#define IDB_CB_ACCIDENTAL_INKEY         365
#define IDB_CB_ACCIDENTAL_NATURAL       366
#define IDB_CB_ACCIDENTALS_SHARP        367
#define IDB_BASS_CLEFF                  368
#define IDB_TREBLE_CLEFF                369
#define IDB_CB_KEY_AFMAJ                370
#define IDB_CB_KEY_AMAJ                 371
#define IDB_CB_KEY_BFMAJ                372
#define IDB_CB_KEY_BMAJ                 373
#define IDB_CB_KEY_CFMAJ                374
#define IDB_CB_KEY_CMAJ                 375
#define IDB_CB_KEY_CSMAJ                376
#define IDB_CB_KEY_DFMAJ                377
#define IDB_CB_KEY_DMAJ                 378
#define IDB_CB_KEY_EFMAJ                379
#define IDB_CB_KEY_EMAJ                 380
#define IDB_CB_KEY_FMAJ                 381
#define IDB_CB_KEY_FSMAJ                382
#define IDB_CB_KEY_GFMAJ                383
#define IDB_CB_KEY_GMAJ                 384
#define IDB_CB_DECORATIONS_NONE_SEL     385
#define IDD_DIALOG_INSTUMENT_MIDI       387
#define IDD_DIALOG_MIDIOUT              389
#define IDB_BITMAP2                     391
#define IDD_MIDI_IN_DISPATCH            392
#define IDD_DIALOG_SELECT_MIDI_IN       394
#define IDR_TX816_EDIT                  396
#define IDI_ICON1                       399
#define IDB_BITMAP5                     400
#define IDB_BITMAP6                     401
#define IDI_ICON2                       403
#define IDI_ICON3                       404
#define IDI_ICON4                       405
#define IDR_MUSIC_EDIT                  405
#define IDB_DX7_ALG20                   406
#define IDB_DX7_ALG01                   407
#define IDB_DX7_ALG2                    408
#define IDB_DX7_ALG02                   408
#define IDB_DX7_ALG03                   409
#define IDB_DX7_ALG04                   410
#define IDB_DX7_ALG05                   411
#define IDB_DX7_ALG06                   412
#define IDB_DX7_ALG07                   413
#define IDB_DX7_ALG08                   414
#define IDB_DX7_ALG09                   415
#define IDB_DX7_ALG10                   416
#define IDB_DX7_ALG11                   417
#define IDB_DX7_ALG12                   418
#define IDB_DX7_ALG13                   419
#define IDB_DX7_ALG14                   420
#define IDB_DX7_ALG15                   421
#define IDB_DX7_ALG16                   422
#define IDB_DX7_ALG17                   423
#define IDB_DX7_ALG18                   424
#define IDB_DX7_ALG19                   425
#define IDB_DX7_ALG21                   426
#define IDB_DX7_ALG22                   427
#define IDB_DX7_ALG23                   428
#define IDB_DX7_ALG24                   429
#define IDB_DX7_ALG25                   430
#define IDB_DX7_ALG26                   431
#define IDB_DX7_ALG27                   432
#define IDB_DX7_ALG28                   433
#define IDB_DX7_ALG29                   434
#define IDB_DX7_ALG30                   435
#define IDB_DX7_ALG31                   436
#define IDB_Dx7_ALG32                   437
#define IDB_BITMAP7                     439
#define IDB_BITMAP8                     440
#define IDB_TX816_LFO_TRI_0             440
#define IDB_TX816_LFO_SAWDOWN_1         441
#define IDB_TX816_LFO_SAWUP_2           442
#define IDB_TX816_LFO_SQUARE_3          443
#define IDB_TX816_LFO_SINE_4            444
#define IDB_TX816_LFO_SAMPLE_HOLD_5     445
#define IDD_CHORD_EDITOR                446
#define IDC_EDIT_ENTR_STRING            1002
#define IDC_VSB_INST_SELECT             1003
#define IDC_HSB_PATCH                   1004
#define IDC_EDIT_TITLE                  1005
#define IDC_HSB_RANGE                   1006
#define IDC_HSB_CHANNEL                 1007
#define IDC_CHECK_GROUP_ONE             1008
#define IDC_CHECK_GROUP_TWO             1009
#define IDC_CHECK_GROUP_THREE           1010
#define IDC_CHECK_GROUP_FOUR            1011
#define IDC_COMBO_MDIDEVICE             1014
#define IDC_STATIC_PATCH                1015
#define IDC_STATIC_PATCHVALUE           1016
#define IDC_STATIC_RANGE                1017
#define IDC_STATIC_RANGEVALUE           1018
#define IDC_CHANNEL_NAME                1019
#define IDC_STATIC_TRACK                1020
#define IDC_STATIC_CHANNEL_VALUE        1021
#define IDC_COMBO_MIDIOUT_SELECT        1022
#define IDC_STATIC_MOS_BM1              1023
#define IDC_COMBO_DEST_WINDOW           1024
#define IDC_COMBO_SELECT_MIDI_IN        1024
#define IDC_SCROLLBAR_PARAM             1025
#define IDC_EDIT_DISPATCH_DATAONE_LOW   1025
#define IDC_STATIC_PARAM                1026
#define IDC_EDIT_DISPATCH_DATAONE_HIGH  1026
#define IDC_COMBO_SEL_DURATUION         1027
#define IDC_EDIT_DISPATCH_DATATWO_LOW   1027
#define IDC_EDIT_DISPATCH_DATATWO_HIGH  1028
#define IDC_STATIC_PROMT_DUR            1029
#define IDC_COMBO_DISPATCH_MIDUCHANNEL  1029
#define IDC_RADIO_NONE                  1030
#define IDC_COMBO_DISPATCH_COMMAND      1030
#define IDC_RADIO_DOTTED                1031
#define IDC_COMBO_DISPATCH_STATUS       1031
#define IDC_RADIO_TRIPPLET              1032
#define IDC_BUTTON_NEWDISPATCHER        1032
#define IDC_BUTTON_DELETEDISPATCHER     1033
#define IDC_BUTTON_NEXT_DISPATCH        1034
#define IDC_BUTTON_PREV_DISPATCH        1035
#define IDC_STATIC_DISPATCH_DATA1       1036
#define IDC_CHECK_ACCENT                1037
#define IDC_STAIC_DISPATCH_DATA2        1037
#define IDC_EDIT5                       1038
#define IDC_EDIT_DISPATCH_NAME          1038
#define IDC_STATIC_HIGH_VAL             1039
#define IDC_STATIC_LOW_VAL              1040
#define IDC_CHECK_REST                  1041
#define IDC_STATIC_CHANNEL              1041
#define IDC_SCROLLBAR_PTICH             1042
#define IDC_STATIC_STATUS_BYTE          1042
#define IDC_SCROLLBAR_OCTAVE            1043
#define IDC_STATIC_MOS_BM2              1043
#define IDC_STATIC_COMMAND              1043
#define IDC_STATIC_PITCH                1044
#define IDC_STATIC_MOS_BM3              1044
#define IDC_COMBO1                      1044
#define IDC_STATIC_OCTAVE               1045
#define IDC_STATIC_MOS_BM4              1045
#define IDC_COMBO2                      1045
#define IDC_RADIO_ACCEDENTAL            1046
#define IDC_STATIC_MOS_BM5              1046
#define IDC_SCROLLBAR1                  1046
#define IDC_RADIO2                      1047
#define IDC_STATIC_MOS_BM6              1047
#define IDC_RADIO3                      1048
#define IDC_STATIC_MOS_BM7              1048
#define IDC_RADIO4                      1049
#define IDC_STATIC_MOS_BM8              1049
#define IDC_COMBO_DURATION              1050
#define IDC_STATIC_MOS_BM9              1050
#define IDC_STATIC_MOS_BM10             1051
#define IDC_STATIC_MOS_BM11             1052
#define ID_COMBO_SELECTOR               1053
#define IDC_STATIC_MOS_BM12             1053
#define IDC_COMBO_SELECTOR              1054
#define IDC_STATIC_MOS_BM13             1054
#define IDC_STATIC_MOS_BM14             1055
#define IDC_STATIC_MOS_BM15             1056
#define IDC_COMBO_MIDI_IN_SELECT        1116
#define IDC_COMBO_MIDI_OUT_SELECT       1117
#define IDC_STATIC_DISP                 1118
#define IDC_COMBO_DLG_INSTRUMENT        2001
#define ID_SETTINGS_TRACKSETTINIGS      32771
#define ID_SETTINGS_MIDIIN              32772
#define ID_SETTINGS_ADDMI               32777
#define ID_SETTINGS_ADDMIDI_OUT         32778
#define ID_SETTINGS_ADDDISPATCHER       32779
#define ID_SETTINGS_ADDDISPATCHER32780  32780
#define ID_FILE_NEW_SONG                32781
#define ID_NEW_NEWTX816EDIT             32782
#define ID_NEW_NEWLAUNCHPAD             32783
#define ID_NEW_NEWLAUNCHCONTROLEDIT     32784
#define MENU_FILE_OPEN                  32785
#define MENU_MS_FILE_SAVE               32786
#define MENU_MS_FILE_OPEN               32787
#define MENU_MS_FILE_SAVE_as            32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        448
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           315
#endif
#endif
